Ensure $oldSessionData is an array before merge
zendframework/zend-session pull request #57
Opened 2016-09-20 08:55 UTC by exptom

If $oldSessionData is a Traversable type of storage rather than a plain array (e.g. `Zend\Session\Storage\SessionStorage` then ArrayUtils::merge would throw an error, Traversable types will be converted to arrays before merge.

This fixes issue #10

2016-09-20 16:25 UTC, samsonasik commented on src/SessionManager.php
> +            if(!is_array($oldSessionData)) {
space after if

2016-09-20 16:26 UTC, samsonasik commented on src/SessionManager.php
> +
remove whitespace

2016-09-20 16:26 UTC, samsonasik requested changes
cs

2016-09-20 16:27 UTC, samsonasik commented
also, it seems require tests

2017-06-19 14:17 UTC, weierophinney requested changes
As noted by @samsonasik:

- We need unit tests.
- Please use the provided phpcs configuration to fix CS issues (`composer cs-fix`).

2017-06-20 09:41 UTC, Ocramius commented
@exptom please don't merge upstream branches into yours: rebase instead.

2017-06-20 09:42 UTC, exptom commented
@Ocramius Apologies! How can I fix this now?

2017-06-20 09:42 UTC, samsonasik commented
@exptom I created a blog post about rebase feature branch: https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

2017-06-20 09:44 UTC, exptom commented
@samsonasik Thank you, is there a way to easily revert back the pushed merged so that I can rebase instead?

2017-06-20 09:59 UTC, samsonasik commented
First, do reset --hard latest commit ( merge commit ): 

```
git reset --hard HEAD~1
```

then, switch to master branch and pull upstream master:

```
git checkout master && git pull https://github.com/zendframework/zend-session.git master
```

then, switch to your branch again and rebase:

```
git checkout patch-1 && git rebase master
```

You will get conflict, then you need to fix the conflict indicating by "<<<<<<< HEAD", don't commit anything at this phase.

After all conflicted files resolved, do:

```
git add . && git rebase --continue && git push --force origin patch-1
```

2017-06-20 10:19 UTC, exptom commented
@samsonasik I think I have fixed it
@weierophinney Thanks for the reminder, I had forgotten to come back to this ticket.
I have applied the CS fixes and added a unit test.

I have had to make a change though as the setUp() method was creating a new instance of SessionManager and that was causing problems testing the storage. When the SessionManager instance is created it registers a shutdown function but because I need to create a new SessionManager to test the particular storage object it was still causing the shutdown function registered in the setUp() to run and causing the test to fail. I have moved the SessionManager instantiation into the individual tests.

2017-08-12 12:37 UTC, roelvanduijnhoven commented
Also encounter this while upgradinging from ZF2 to ZF3. Not sure how to proceed. For the time being I'll use the following *fix*. But obviously not valid for production:

> 'type' => \Zend\Session\Storage\ArrayStorage::class,

2017-10-03 12:09 UTC, zf2timo commented
I encounter this issue with the `\Zend\Session\Storage\SessionArrayStorage::class` today.
The suggested workaround from @roelvanduijnhoven did not worked. I still get the error:
> Argument 1 passed to Zend\Stdlib\ArrayUtils::merge() must be of the type array, object given, called in /var/www/html/vendor/zendframework/zend-session/src/SessionManager.php on line 136

I think this PR should be merged in the near feature, because it is already opened for over a year and it occurs when the example configuration from the documentation is used.

2017-11-28 15:46 UTC, weierophinney approved these changes

2017-11-28 15:53 UTC, Xerkus commented on src/SessionManager.php
> +                $oldSessionData = $oldSessionData->toArray();
This assumes $oldSessionsData from $_SESSION superglobal is an object that implements `toArray()` method.
Can it be something else?

2017-11-28 16:00 UTC, merged

2017-11-28 16:00 UTC, weierophinney commented
Thanks, @exptom