Remove `use Zend\Session\SessionManager;`
zendframework/zend-session pull request #87
Opened 2017-09-29 13:41 UTC by Nenglish7

Remove `use Zend\Session\SessionManager;` in second example as it is being called twice

2017-10-09 20:59 UTC, samsonasik approved these changes

2017-10-09 21:00 UTC, webimpress commented
@samsonasik @Nenglish7  I think the first entry should be removed, to keep alphabetical order.

2017-10-09 21:00 UTC, samsonasik requested changes
@Nenglish7 the removed one can be the first one so use statement be in sort order

2017-10-23 00:59 UTC, Awixe approved these changes

2017-11-28 16:23 UTC, closed without merging

2017-11-28 16:24 UTC, weierophinney commented
Thanks, @Nenglish7